baseURL = 'https://icons.shuyuart.com/'
locale = "zh-TW"
title = "Shuyu's Pixel Art Icons"
[params]
    brandName = "SHUYU'S"
    mainTitle = "PIXEL ART ICONS"
    subtitle = "A collection of tiny things."
    description = "探索台灣風味與日常物件的像素圖庫"
[permalinks]
  pages = "/:slug/"
[markup.goldmark.renderer]
  unsafe = true