baseURL = 'https://icons.shuyuart.com/'
languageCode = 'zh-TW'
title = "Shuyu's Pixel Shelf"
[params]
    subtitle = "A collection of tiny things."
    description = "探索台灣風味與日常物件的像素圖庫"
[permalinks]
  pages = "/:slug/"